#!/usr/bin/env bash

# reading user input then displaying text on the screen
echo "enter the process you want to view."
read e && echo "------------------------" && echo "     R E S U L T S"
echo "------------------------"

# main code
ps -eF | awk -F ' ' '{print $11}' | grep -i $e
