#!/usr/bin/env bash

####################################
####################################
# C R E A T E D    BY    H E X I S #
####################################
####################################

# reading user input then displaying text on the screen
echo "enter the process you want to view."
read e && echo "------------------------" && echo "     R E S U L T S"
echo "------------------------"

# main code
ps -eF | awk -F ' ' '{print $11}' | grep -i $e
